/*
 * This source file was generated by the Gradle 'init' task
 */
package cantilevermodelmaker;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.joml.Vector3d;
import org.joml.Vector3f;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;

public class App {


    public static void main(String[] args) throws Exception {
        String inPath = "C:\\Users\\julia\\Desktop\\cantilever_4px.bbmodel";
        String outPath = "C:\\Users\\julia\\Desktop\\output.json";

        try (FileReader reader = new FileReader(inPath)) {
            // JSON aus Datei lesen und parsen
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            JsonArray outlinerArray = root.getAsJsonArray("outliner");
            JsonArray elements = root.getAsJsonArray("elements");

            Map<String, Vector3d> rotations = getRotations(outlinerArray, new Vector3d());

            System.out.println("Elements Count: " + elements.size());

            for (int i = 0; i < elements.size(); i++) {
                JsonObject element = elements.get(i).getAsJsonObject();
                if (!element.has("vertices")) continue;

                JsonObject vertices = element.getAsJsonObject("vertices");
                System.out.println("  Vertices Count: " + vertices.size()); 
                for (String key : vertices.keySet()) {
                    JsonArray coords = vertices.getAsJsonArray(key);
                    Vector3d vec = new Vector3d(coords.get(0).getAsDouble(), coords.get(1).getAsDouble(), coords.get(2).getAsDouble());

                    if (vec.z > -20) continue;


                    String targetUuid = element.get("uuid").getAsString();
                    if (rotations.containsKey(targetUuid)) {
                        // Winkel in Grad
                        double angleDegrees = -rotations.get(targetUuid).x;

                        // Umwandeln in Radiant (für trigonometrische Funktionen)
                        double angleRadians = Math.toRadians(angleDegrees);

                        // Länge der Verschiebung (z. B. 10 Einheiten)
                        double length = 10.0f;

                        // Berechnung der Verschiebungskomponenten
                        double deltaY = (Math.cos(angleRadians) * length);
                        double deltaZ = (Math.sin(angleRadians) * length);

                        // Neuen Vektor berechnen
                        vec = new Vector3d(vec).add(0, deltaY, deltaZ);
                    } else {                        
                        vec.add(0, -10, 0);
                    }

                    coords.set(0, new JsonPrimitive(vec.x));
                    coords.set(1, new JsonPrimitive(vec.y));
                    coords.set(2, new JsonPrimitive(vec.z));
                    vertices.add(key, coords);
                }
                element.add("vertices", vertices);
                elements.set(i, element);
            }
            root.add("elements", elements);

            try (FileWriter writer = new FileWriter(outPath)) {
                writer.write(root.toString());
                System.out.println("Das JSON wurde erfolgreich in die Datei 'output.json' geschrieben.");
            } catch (IOException e) {
                e.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static Map<String, Vector3d> getRotations(JsonArray input, Vector3d currentRotation) {
        Map<String, Vector3d> result = new HashMap<>();
        Iterator<JsonElement> elements = input.iterator();        
        while (elements.hasNext()) {
            JsonElement e = elements.next();
            if (e.isJsonObject()) {
                JsonObject o = e.getAsJsonObject();
                JsonArray a = o.getAsJsonArray("rotation");
                Vector3d rot = a == null ? new Vector3d() : new Vector3d(a.get(0).getAsDouble(), a.get(1).getAsDouble(), a.get(2).getAsDouble());
                result.putAll(getRotations(o.getAsJsonArray("children"), new Vector3d(currentRotation).add(rot)));
            } else {
                result.put(e.getAsString(), currentRotation);
            }
        }
        return result;
    }
}
